version: "3.8"

services:
  flaskapp:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./appFlask:/app/appFlask
      - ./requirements.txt:/app/requirements.txt
    environment:
      - FLASK_ENV=development
